version: "3"
services:
  app:
    build: .
    restart: always
    environment:
      NODE_ENV: production
      DB_HOST:  ec2-13-57-52-59.us-west-1.compute.amazonaws.com
    ports:
      - "80:3003"

